/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import UpperEssential.UpperEssentialLookAndFeel;
import baseDatos.OperacionesBaseDatos;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modelo.MedidaPliegue;
import modelo.Paciente;

/**
 *
 * @author agg
 */
public class MedidasPliegueDialogo extends javax.swing.JDialog {

    public Paciente paciente;
    private MedidaPliegue pliegue;
    private boolean actualizar;
    private OperacionesBaseDatos op;
    TablaMedidasPliegueDialogo tabla;

    public MedidasPliegueDialogo(java.awt.Frame parent, boolean modal) throws UnsupportedLookAndFeelException {
        super(parent, modal);
        UIManager.setLookAndFeel(new UpperEssentialLookAndFeel());
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * Creates new form MedidasPliegueDialogo
     */
    public MedidasPliegueDialogo(java.awt.Frame parent, boolean modal, Paciente paciente) throws UnsupportedLookAndFeelException {
        super(parent, modal);
        UIManager.setLookAndFeel(new UpperEssentialLookAndFeel());
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.pliegue = new MedidaPliegue();
        this.paciente = paciente;
        this.actualizar = false;
        op = new OperacionesBaseDatos();
        menuEditar.setVisible(false);

    }

    public MedidasPliegueDialogo(java.awt.Frame parent, boolean modal, Paciente paciente, TablaMedidasPliegueDialogo tabla) throws UnsupportedLookAndFeelException {
        super(parent, modal);
        UIManager.setLookAndFeel(new UpperEssentialLookAndFeel());
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.pliegue = new MedidaPliegue();
        this.paciente = paciente;
        this.actualizar = false;
        this.tabla = tabla;
        op = new OperacionesBaseDatos();
        menuEditar.setVisible(false);
    }

    public MedidasPliegueDialogo(java.awt.Frame parent, boolean modal, MedidaPliegue pliegue) throws UnsupportedLookAndFeelException {
        super(parent, modal);
        UIManager.setLookAndFeel(new UpperEssentialLookAndFeel());
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        this.pliegue = pliegue;
        this.actualizar = true;
        op = new OperacionesBaseDatos();
        rellenarCampos();
    }

    private void rellenarCampos() {
        if (pliegue != null && actualizar) {
            textAbdominal.setText(String.valueOf(pliegue.getAbdominal()));
            textPierna.setText(String.valueOf(pliegue.getMedidaPlieguePierna()));
            textMuslo.setText(String.valueOf(pliegue.getMuslo()));
            textSubescapular.setText(String.valueOf(pliegue.getSubescapular()));
            textSuprailiaco.setText(String.valueOf(pliegue.getSuprailiaco()));
            textTricipital.setText(String.valueOf(pliegue.getTricipital()));

            textAbdominal.setEditable(false);
            textPierna.setEditable(false);
            textPierna.setEditable(false);
            textMuslo.setEditable(false);
            textSubescapular.setEditable(false);
            textSuprailiaco.setEditable(false);
            textTricipital.setEditable(false);
            botonAceptar.setVisible(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textTricipital = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textPierna = new javax.swing.JTextField();
        textAbdominal = new javax.swing.JTextField();
        textSubescapular = new javax.swing.JTextField();
        textSuprailiaco = new javax.swing.JTextField();
        textMuslo = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEditar = new javax.swing.JMenu();
        menuActulizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel1.setText("Pliegue tricipital");

        textTricipital.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTricipitalKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel2.setText("Pliegue pierna");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel3.setText("Pliegue abdominal");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel4.setText("Pliegue subescapular");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel5.setText("Pliegue suprailíaco");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel6.setText("Pliegue muslo");

        textPierna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPiernaKeyTyped(evt);
            }
        });

        textAbdominal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAbdominalKeyTyped(evt);
            }
        });

        textSubescapular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSubescapularKeyTyped(evt);
            }
        });

        textSuprailiaco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSuprailiacoKeyTyped(evt);
            }
        });

        textMuslo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textMusloKeyTyped(evt);
            }
        });

        botonAceptar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        botonAceptar.setText("ACEPTAR");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("MEDIDAS PLIEGUES ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPierna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTricipital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAbdominal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSubescapular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSuprailiaco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMuslo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTricipital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textPierna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textAbdominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textSubescapular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textSuprailiaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMuslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addGap(40, 40, 40))
        );

        menuEditar.setText("EDITAR");

        menuActulizar.setText("ACTUALIZAR");
        menuActulizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActulizarActionPerformed(evt);
            }
        });
        menuEditar.add(menuActulizar);

        jMenuBar1.add(menuEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void textTricipitalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTricipitalKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && textTricipital.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_textTricipitalKeyTyped

    private void textPiernaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPiernaKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && textPierna.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_textPiernaKeyTyped

    private void textAbdominalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAbdominalKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && textAbdominal.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_textAbdominalKeyTyped

    private void textSubescapularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSubescapularKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && textSubescapular.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_textSubescapularKeyTyped

    private void textSuprailiacoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSuprailiacoKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && textSuprailiaco.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_textSuprailiacoKeyTyped

    private void textMusloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMusloKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && textMuslo.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_textMusloKeyTyped

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String abdominal = textAbdominal.getText();
        String pierna = textPierna.getText();
        String muslo = textMuslo.getText();
        String subescapular = textSubescapular.getText();
        String suprailiaco = textSuprailiaco.getText();
        String tricipital = textTricipital.getText();

        if (!abdominal.equalsIgnoreCase("")) {
            pliegue.setAbdominal(Float.parseFloat(abdominal));
        }
        if (!pierna.equalsIgnoreCase("")) {
            pliegue.setMedidaPlieguePierna((Float.parseFloat(pierna)));
        }
        if (!muslo.equalsIgnoreCase("")) {
            pliegue.setMuslo(Float.parseFloat(muslo));
        }
        if (!subescapular.equalsIgnoreCase("")) {
            pliegue.setSubescapular(Float.parseFloat(subescapular));
        }
        if (!suprailiaco.equalsIgnoreCase("")) {
            pliegue.setSuprailiaco(Float.parseFloat(suprailiaco));
        }
        if (!tricipital.equalsIgnoreCase("")) {
            pliegue.setTricipital(Float.parseFloat(tricipital));
        }

        if (actualizar) {
            op.actulizarMedidasPliegue(pliegue);
        } else {
            pliegue.setFecha(new Date());
            pliegue.setPaciente(paciente);
            op.insertarMedidasPliegue(pliegue);
        }
        if (tabla != null) {
            tabla.rellenarTabla();
        }
        dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void menuActulizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActulizarActionPerformed
        textAbdominal.setEditable(true);
        textPierna.setEditable(true);
        textPierna.setEditable(true);
        textMuslo.setEditable(true);
        textSubescapular.setEditable(true);
        textSuprailiaco.setEditable(true);
        textTricipital.setEditable(true);
        botonAceptar.setVisible(true);

    }//GEN-LAST:event_menuActulizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedidasPliegueDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedidasPliegueDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedidasPliegueDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedidasPliegueDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MedidasPliegueDialogo dialog = null;
                try {
                    dialog = new MedidasPliegueDialogo(new javax.swing.JFrame(), true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MedidasPliegueDialogo.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem menuActulizar;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JTextField textAbdominal;
    private javax.swing.JTextField textMuslo;
    private javax.swing.JTextField textPierna;
    private javax.swing.JTextField textSubescapular;
    private javax.swing.JTextField textSuprailiaco;
    private javax.swing.JTextField textTricipital;
    // End of variables declaration//GEN-END:variables
}
