/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import UpperEssential.UpperEssentialLookAndFeel;
import baseDatos.OperacionesBaseDatos;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modelo.MedidasNormales;
import modelo.Paciente;

/**
 *
 * @author agg
 */
public class MedidasNormalesDialogo extends javax.swing.JDialog {

    private Paciente paciente;
    private MedidasNormales normales;
    private boolean actualizar;
    private VistaPacienteGeneral vista;
    private OperacionesBaseDatos op=new OperacionesBaseDatos();
    /**
     * Creates new form MedidasNormalesDialogo
     */
    public MedidasNormalesDialogo(java.awt.Frame parent, boolean modal) throws UnsupportedLookAndFeelException {
        super(parent, modal);
       UIManager.setLookAndFeel(new UpperEssentialLookAndFeel());
        initComponents();
         this.setResizable(false);
         this.setLocationRelativeTo(null);
    }

    
     public MedidasNormalesDialogo(java.awt.Frame parent, boolean modal,Paciente paciente) throws UnsupportedLookAndFeelException {
        super(parent, modal);
       UIManager.setLookAndFeel(new UpperEssentialLookAndFeel());
        initComponents();
         this.setResizable(false);
         this.setLocationRelativeTo(null);
         this.paciente=paciente;
         actualizar=false;
         normales=new MedidasNormales();
         menuEditar.setVisible(false);
    }
     
      public MedidasNormalesDialogo(java.awt.Frame parent, boolean modal,Paciente paciente,VistaPacienteGeneral vista) throws UnsupportedLookAndFeelException {
        super(parent, modal);
       UIManager.setLookAndFeel(new UpperEssentialLookAndFeel());
        initComponents();
         this.setResizable(false);
         this.setLocationRelativeTo(null);
         this.paciente=paciente;
         actualizar=false;
         normales=new MedidasNormales();
         menuEditar.setVisible(false);
         this.vista=vista;
    }
     
      public MedidasNormalesDialogo(java.awt.Frame parent, boolean modal,MedidasNormales normales) throws UnsupportedLookAndFeelException {
        super(parent, modal);
       UIManager.setLookAndFeel(new UpperEssentialLookAndFeel());
        initComponents();
         this.setResizable(false);
         this.setLocationRelativeTo(null);
         this.normales=normales;
         actualizar=true;
         recargarTextfields();
    }
    
      private void recargarTextfields(){
          if(normales!=null&&actualizar){
              textAbdomen.setText(String.valueOf(normales.getMedidaAbdomen()));
              textAgua.setText(String.valueOf(normales.getPorcentajeAgua()));
              textAltura.setText(String.valueOf(normales.getAltura()));
              textBrazo.setText(String.valueOf(normales.getMedidaBrazo()));
              textCadera.setText(String.valueOf(normales.getMedidaCadera()));
              textCintura.setText(String.valueOf(normales.getMedidaCintura()));
              textGrasa.setText(String.valueOf(normales.getPorcentajeGrasa()));
              textMasaMuscular.setText(String.valueOf(normales.getPorcentajeMasaMuscular()));
              textMunyeca.setText(String.valueOf(normales.getMedidaMunyeca()));
              textMuslo.setText(String.valueOf(normales.getMedidaMuslo()));
              textPecho.setText(String.valueOf(normales.getMedidaPecho()));
              textPeso.setText(String.valueOf(normales.getPeso()));
              textGemelo.setText(String.valueOf(normales.getMedidaGemelo()));
              
              textAbdomen.setEditable(false);
              textAgua.setEditable(false);
              textAltura.setEditable(false);
              textBrazo.setEditable(false);
              textCadera.setEditable(false);
              textCintura.setEditable(false);
              textGrasa.setEditable(false);
              textMasaMuscular.setEditable(false);
              textMunyeca.setEditable(false);
              textMuslo.setEditable(false);
              textPecho.setEditable(false);
              textPeso.setEditable(false);
              textGemelo.setEditable(false);
              botonAceptar.setVisible(false);
              
          }
      }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textCintura = new javax.swing.JTextField();
        textAbdomen = new javax.swing.JTextField();
        textCadera = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textPecho = new javax.swing.JTextField();
        textMuslo = new javax.swing.JTextField();
        textBrazo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textGemelo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textMasaMuscular = new javax.swing.JTextField();
        textGrasa = new javax.swing.JTextField();
        textMunyeca = new javax.swing.JTextField();
        textAltura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textPeso = new javax.swing.JTextField();
        textAgua = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEditar = new javax.swing.JMenu();
        menuActualizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, 18));
        jLabel2.setText("MEDIDAS PACIENTE");

        jSeparator1.setBorder(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel3.setText("Cintura");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel6.setText("Abdomen");

        textCintura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCinturaKeyTyped(evt);
            }
        });

        textAbdomen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAbdomenKeyTyped(evt);
            }
        });

        textCadera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCaderaKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel8.setText("Pecho");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel7.setText("Cadera");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel4.setText("Muslo");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel5.setText("Brazo");

        textPecho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPechoKeyTyped(evt);
            }
        });

        textMuslo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textMusloKeyTyped(evt);
            }
        });

        textBrazo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBrazoKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel14.setText("Gemelo");

        textGemelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textGemeloKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCintura, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(textAbdomen)
                    .addComponent(textCadera)
                    .addComponent(textMuslo)
                    .addComponent(textBrazo)
                    .addComponent(textPecho)
                    .addComponent(textGemelo))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textPecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textCintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textAbdomen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textCadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textMuslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textGemelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel9.setText("Altura (m)");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel10.setText("Muñeca");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel12.setText("Grasa %");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel13.setText("Masa muscular %");

        textMasaMuscular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textMasaMuscularKeyTyped(evt);
            }
        });

        textGrasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textGrasaKeyTyped(evt);
            }
        });

        textMunyeca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textMunyecaKeyTyped(evt);
            }
        });

        textAltura.setToolTipText("Introducir la altura del paciente en metros ej 1.75 metros");
        textAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAlturaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel1.setText("Peso");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel11.setText("Agua %");

        textPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPesoKeyTyped(evt);
            }
        });

        textAgua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAguaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textMasaMuscular, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(textMunyeca, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textAltura, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPeso, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textAgua)
                    .addComponent(textGrasa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textMunyeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textGrasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textMasaMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSeparator2.setBackground(java.awt.Color.black);
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(null);

        botonAceptar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        botonAceptar.setText("ACEPTAR");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        menuEditar.setText("EDITAR");

        menuActualizar.setText("ACTUALIZAR");
        menuActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizarActionPerformed(evt);
            }
        });
        menuEditar.add(menuActualizar);

        jMenuBar1.add(menuEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void textPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPesoKeyTyped
       if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textPeso.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textPesoKeyTyped

    private void textCinturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCinturaKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textCintura.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textCinturaKeyTyped

    private void textMusloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMusloKeyTyped
      if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textMuslo.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textMusloKeyTyped

    private void textPechoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPechoKeyTyped
       if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textPecho.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textPechoKeyTyped

    private void textAbdomenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAbdomenKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textAbdomen.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textAbdomenKeyTyped

    private void textCaderaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCaderaKeyTyped
       if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textCadera.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textCaderaKeyTyped

    private void textBrazoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBrazoKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textBrazo.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textBrazoKeyTyped

    private void textAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAlturaKeyTyped
       if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textAltura.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textAlturaKeyTyped

    private void textMunyecaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMunyecaKeyTyped
       if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textMunyeca.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textMunyecaKeyTyped

    private void textGrasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textGrasaKeyTyped
       if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textGrasa.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textGrasaKeyTyped

    private void textAguaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAguaKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textAgua.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textAguaKeyTyped

    private void textMasaMuscularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMasaMuscularKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textMasaMuscular.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textMasaMuscularKeyTyped

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String abdomen = textAbdomen.getText();
        String agua = textAgua.getText();
        String altura = textAltura.getText();
        String brazo = textBrazo.getText();
        String cadera  = textCadera.getText();
        String cintura = textCintura.getText();
        String grasa = textGrasa.getText();
        String masaMuscular = textMasaMuscular.getText();
        String munyeca = textMunyeca.getText();
        String muslo = textMuslo.getText();
        String pecho = textPecho.getText();
        String peso = textPeso.getText();
        String gemelo= textGemelo.getText();
        
        
        if(!abdomen.equalsIgnoreCase("")){
            normales.setMedidaAbdomen(Float.parseFloat(abdomen));
        }
        if(!agua.equalsIgnoreCase("")){
            normales.setPorcentajeAgua(Float.parseFloat(agua));
        }
        if(!altura.equalsIgnoreCase("")){
            normales.setAltura(Float.parseFloat(altura));
        }
        if(!brazo.equalsIgnoreCase("")){
            normales.setMedidaBrazo(Float.parseFloat(brazo));
        }
        if(!cadera.equalsIgnoreCase("")){
            normales.setMedidaCadera(Float.parseFloat(cadera));
        }
        
        if(!cintura.equalsIgnoreCase("")){
            normales.setMedidaCintura(Float.parseFloat(cintura));
        }
        if(!grasa.equalsIgnoreCase("")){
            normales.setPorcentajeGrasa(Float.parseFloat(grasa));
        }
        if(!masaMuscular.equalsIgnoreCase("")){
            normales.setPorcentajeMasaMuscular(Float.parseFloat(masaMuscular));
        }
        if(!munyeca.equalsIgnoreCase("")){
            normales.setMedidaMunyeca(Float.parseFloat(munyeca));
        }
        if(!muslo.equalsIgnoreCase("")){
            normales.setMedidaPecho(Float.parseFloat(muslo));
        }
        if(!pecho.equalsIgnoreCase("")){
            normales.setMedidaPecho(Float.parseFloat(pecho));
        }
        if(!peso.equalsIgnoreCase("")){
            normales.setPeso(Float.parseFloat(peso));
        }
        if(!gemelo.equalsIgnoreCase("")){
            normales.setMedidaGemelo(Float.parseFloat(gemelo));
        }
        if(!muslo.equalsIgnoreCase("")){
            normales.setMedidaMuslo(Float.parseFloat(muslo));
        }
        if(actualizar){
            op.actualizarMedidasNormales(normales);
        }else{
            normales.setFecha(new Date());
            normales.setPaciente(paciente);
            
            op.insertarMedidasNormales(normales);
        }
        
        dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void textGemeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textGemeloKeyTyped
         if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        
        if(evt.getKeyChar()=='.'&&textGemelo.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_textGemeloKeyTyped

    private void menuActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarActionPerformed
       
        textAbdomen.setEditable(true);
              textAgua.setEditable(true);
              textAltura.setEditable(true);
              textBrazo.setEditable(true);
              textCadera.setEditable(true);
              textCintura.setEditable(true);
              textGrasa.setEditable(true);
              textMasaMuscular.setEditable(true);
              textMunyeca.setEditable(true);
              textMuslo.setEditable(true);
              textPecho.setEditable(true);
              textPeso.setEditable(true);
              textGemelo.setEditable(true);
              botonAceptar.setVisible(true);
              
    }//GEN-LAST:event_menuActualizarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(vista!=null){
            try {
                vista.rellenarCampos();
            } catch (IOException ex) {
                Logger.getLogger(MedidasNormalesDialogo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedidasNormalesDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedidasNormalesDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedidasNormalesDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedidasNormalesDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MedidasNormalesDialogo dialog = null;
                try {
                    dialog = new MedidasNormalesDialogo(new javax.swing.JFrame(), true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MedidasNormalesDialogo.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem menuActualizar;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JTextField textAbdomen;
    private javax.swing.JTextField textAgua;
    private javax.swing.JTextField textAltura;
    private javax.swing.JTextField textBrazo;
    private javax.swing.JTextField textCadera;
    private javax.swing.JTextField textCintura;
    private javax.swing.JTextField textGemelo;
    private javax.swing.JTextField textGrasa;
    private javax.swing.JTextField textMasaMuscular;
    private javax.swing.JTextField textMunyeca;
    private javax.swing.JTextField textMuslo;
    private javax.swing.JTextField textPecho;
    private javax.swing.JTextField textPeso;
    // End of variables declaration//GEN-END:variables
}
